name = 'Tipuana Tipu'
groups = [
  'Tree'
]
commonNames = [
  'tipa',
  'rosewood',
  'pride of Bolivia'
]
properties = [
  'fastGrowing',
  'goldenFlowers',
  'greenLeaves',
]
inputs = [
  'warmth'
]
outputs = [
  'flowers',
  'nectar',
  'saponins',
  'seeds',
  'tannins',
]