name = 'Trifolium'
commonNames = [
  'clover'
]
properties = [
  'shortLived',
  'short',
]
inputs = [
  'phosphorus',
  'calcium'
]
outputs = [
  'beeAttractor',
  'protein',
  'phosphorus',
  'calcium',
  'livingMulch',
  'coverCrop'
]