name = 'Brassica oleracea var. gemmifera'
groups = [
]
commonNames = [
  'brussel sprouts',
]
properties = [
  'green',
  'helix'
]
inputs = [
  'calcium',
  'iron',
  'magnesium',
  'manganese',
  'phosphorus',
  'potassium',
  'sodium',
  'zinc',
  'nitrogen'
]
outputs = [
  'vitaminA',
  'vitaminB1',
  'vitaminB2',
  'vitaminB3',
  'vitaminB5',
  'vitaminB6',
  'vitaminB9',
  'choline',
  'vitaminC',
  'vitaminE',
  'vitaminK',
  'calcium',
  'iron',
  'magnesium',
  'manganese',
  'phosphorus',
  'potassium',
  'sodium',
  'zinc',
  'sulforaphane'
]
edible = [
  'sprouts',
]
pests = [
 'CabbageWorm'
]